name: Feature request
description: Suggest an idea for Nativefier
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: homework
    attributes:
      label: Homework
      options:
        - label: I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
        - label: I searched existing issues, open & closed. Yes, my feature request is new.
        - label: I'm using the latest version available at https://github.com/nativefier/nativefier/releases
    validations:
      required: false
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem statement
      description: A clear and concise description of what the problem is.
      value: |
        For example: *Nativefier should [...]. I need it because [...]. Existing options [...] are not exactly what I want, because [...]*

        If related to a Nativefier config, provide your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

        ```
        nativefier --verbose --some-option https://mysite.com
        <paste your verbose build logs, if relevant to your feature request>
        ```
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative solutions
      description: A clear and concise description of workarounds you've considered/tried.
  - type: input
    id: nativefier-version
    attributes:
      label: Nativefier version
      description: "Output of `nativefier --version`"
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: "Output of `node --version`"
  - type: input
    id: npm-version
    attributes:
      label: npm version
      description: "Output of `npm --version`"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "For example: Windows 10 build 1809"
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any additional information that would be relevant. 
      placeholder: "For example: \"I'm behind a proxy, with configuration X and protocol Y\""
    validations:
      required: false