name: Question
description: Ask for help
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: homework
    attributes:
      label: Homework
      options:
        - label: I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
        - label: I searched existing issues, open & closed. Yes, my question is new.
        - label: I'm using the latest version available at https://github.com/nativefier/nativefier/releases
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Your question, expressed clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: "If you already have a Nativefier command you're struggling with, paste ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:"
      value: |
        ```
        nativefier --verbose --some-option https://mysite.com
        <paste your verbose build logs, if relevant to your question>
        ```
    validations:
      required: false
  - type: textarea
    id: debug-info
    attributes:
      label: Debug info
      description: |
        If applicable,

        - Console logs of your attempted `nativefier` build command, with `--verbose` flag
        - Error messages
        - Screenshots
        - Anything else relevant!
  - type: input
    id: nativefier-version
    attributes:
      label: Nativefier version
      description: "Output of `nativefier --version`"
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: "Output of `node --version`"
  - type: input
    id: npm-version
    attributes:
      label: npm version
      description: "Output of `npm --version`"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "For example: Windows 10 build 1809"
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any additional information that would be relevant. 
      placeholder: "For example: \"I'm behind a proxy, with configuration X and protocol Y\""
    validations:
      required: false